# Generated by Django 3.0.1 on 2020-01-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200104_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
