# Generated by Django 3.0.1 on 2020-01-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_addproduct_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
