# Generated by Django 3.0.1 on 2020-01-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_user_user_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_dp',
            field=models.ImageField(upload_to='images2/'),
        ),
    ]
