# Generated by Django 3.0.1 on 2020-01-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200115_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_dp',
        ),
    ]
