# Generated by Django 3.0.1 on 2020-01-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_user_user_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
