# Generated by Django 3.0.1 on 2020-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_addproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
