# Generated by Django 3.0.1 on 2020-01-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200116_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
