# Generated by Django 3.0.1 on 2020-01-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200120_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
            preserve_default=False,
        ),
    ]
