# Generated by Django 3.0.1 on 2020-01-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200122_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='rdate',
            field=models.DateField(null=True),
        ),
    ]
