# Generated by Django 3.0.1 on 2020-03-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
